import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EvoluProvider } from "@evolu/react";
import { evolu } from "@/db/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-svh">
      <body className={(inter.className, "min-h-svh")}>{children}</body>
    </html>
  );
}
