/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xYHqD5MkVkT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
'use client'

import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { JSX, SVGProps } from 'react'
import { ChevronRight, Cloud } from 'lucide-react'
import { useSession } from '@/lib/auth-client'

export function TopNavbar() {
    const { data: session } = useSession()

    const callbackUrl =
        process.env.NODE_ENV === 'production'
            ? 'https://' + process.env.NEXT_PUBLIC_VERCEL_URL
            : 'http://localhost:3000'

    return (
        <nav className="fixed flex justify-center items-center w-lvw top-0 z-50 bg-white shadow-sm dark:bg-gray-950/90">
            <div className="w-full max-w-7xl px-4">
                <div className="flex justify-between h-14 items-center">
                    <Link
                        href="/"
                        className="flex items-center"
                        prefetch={false}
                    >
                        <Cloud className="h-6 w-6 mr-2" />
                        <span className="font-bold self-center">Aether</span>
                    </Link>
                    <nav className="hidden md:flex gap-4">
                        <Link
                            href="/features"
                            className="font-medium flex items-center text-sm transition-colors hover:underline"
                            prefetch={false}
                        >
                            Features
                        </Link>
                        <Link
                            href="/pricing"
                            className="font-medium flex items-center text-sm transition-colors hover:underline"
                            prefetch={false}
                        >
                            Pricing
                        </Link>
                        {/* <Link
                            href="#"
                            className="font-medium flex items-center text-sm transition-colors hover:underline"
                            prefetch={false}
                        >
                            Contact
                        </Link> */}
                    </nav>
                    <div className="flex items-center gap-4">
                        {session?.user ? (
                            <Button asChild>
                                <Link href="/app" className="flex items-center">
                                    Go to app <ChevronRight />
                                </Link>
                            </Button>
                        ) : (
                            <div className="flex gap-x-2">
                                <Button asChild>
                                    <Link
                                        href="/sign-in"
                                        className="flex items-center"
                                    >
                                        Sign in
                                    </Link>
                                </Button>
                                <Button variant="secondary" asChild>
                                    <Link
                                        href="/sign-up"
                                        className="flex items-center"
                                    >
                                        Sign up
                                    </Link>
                                </Button>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </nav>
    )
}

function MountainIcon(
    props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    )
}
